
_DICO = {
    "00": "",
    "0": "zéro",
    "1": "un",
    "01": "un",
    "2": "deux",
    "02": "deux",
    "3": "trois",
    "03": "trois",
    "4": "quatre",
    "04": "quatre",
    "5": "cinq",
    "05": "cinq",
    "6": "six",
    "06": "six",
    "7": "sept",
    "07": "sept",
    "8": "huit",
    "08": "huit",
    "9": "neuf",
    "09": "neuf",
    "10": "dix",
    "11": "onze",
    "12": "douze",
    "13": "treize",
    "14": "quatorze",
    "15": "quinze",
    "16": "seize",
    "17": "dix-sept",
    "18": "dix-huit",
    "19": "dix-neuf",
    "20": "vingt",
    "30": "trente",
    "40": "quarante",
    "50": "cinquante",
    "60": "soixante",
    "80": "quatre-vingt",
}


_PUISSANCES = [
    "mille",
    "million",
    "milliard",
    "billion",
    "billiard",
    "trillion",
    "trilliard",
    "quadrilliard",
    "quintillion",
    "quintilliard",
    "sextillion",
    "sextilliard",
    "septillion",
    "septilliard",
    "octillion",
    "octilliard",
    "nonillion",
    "nonilliard",
    "décillion",
    "décilliard",
    "unodécillion",
    "unodécilliard",
    "duodécillion",
    "duodécilliard",
    "trédécillion",
    "trédécilliard"
]
